version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  app:
    build: ./
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    volumes:
      - ./m2_back
    ports:
      - '5000:5000'

networks:
  mongo-compose-network:
    driver: bridge
