version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  app:
    build: .
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    environment:
<<<<<<<<< Temporary merge branch 1
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGODB_URI: mongodb://admin:pass@mongodb:27017/?authSource=admin
      EMAIL: dau.kassymov@aues.kz
      PASSWORD: qazaqway
      SECRET: meirmanov-secret-key

=========
      EMAIL: "dau.kassymov@aues.kz"
      PASSWORD: "qazaqway"
>>>>>>>>> Temporary merge branch 2
    volumes:
      - .:/app
    ports:
      - '8000:8000'

networks:
  mongo-compose-network:
    driver: bridge
